export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const OPEN_PROGRAMS = 'OPEN_PROGRAMS';
export const OPEN_PROGRAMS_SUCCESS = 'OPEN_PROGRAMS_SUCCESS';
export const OPEN_PROGRAMS_FAILURE = 'OPEN_PROGRAMS_FAILURE';

export const PROGRAMS_LIST = 'PROGRAMS_LIST';
export const PROGRAMS_LIST_SUCCESS = 'PROGRAMS_LIST_SUCCESS';
export const PROGRAMS_LIST_FAILURE = 'PROGRAMS_LIST_FAILURE';

export const APPLY_PROGRAM_LIST_SUCCESS = 'APPLY_PROGRAM_LIST_SUCCESS';
export const APPLY_PROGRAM_LIST_FAILURE = 'APPLY_PROGRAM_LIST_FAILURE';


export const SEARCH_PROGRAM_LIST = 'SEARCH_PROGRAM_LIST';
export const SEARCH_PROGRAM_LIST_SUCCESS = 'SEARCH_PROGRAM_LIST_SUCCESS';

export const CREATE_ROUTES = 'CREATE_ROUTES';
export const CREATE_MEETING_INFO = 'CREATE_MEETING_INFO';
export const CREATE_PROGRAM_INFO = 'CREATE_PROGRAM_INFO';

export const CREATE_PROGRAM_FAILURE = 'CREATE_PROGRAM_FAILURE';
export const CREATE_PROGRAM_SUCCESS = 'CREATE_PROGRAM_SUCCESS';

export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
